sudo: false
language: node_js
node_js:
      - '14.18.1'
cache:
     bundler: true
     directories:
        - node_modules
install:
   - rm -rf node_modules
   - rm package-lock.json
   - npm cache clear --force
   - npm install